# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

DEBS_TARBALL = struct(
    revision = "1588005202",
    sha256 = "4f842efc5190bfa1d576b5094fedfdef9ac17cfe214ffe5e43a0e0b4e2a4a3a3",
)

CACERTS = struct(
    revision = "1588005202",
    sha256 = "7b222422e7ef775c9b85232a4ece9612a6835ba1439efe915f4e4a288b5dfccc",
)
