# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

DEBS_TARBALL = struct(
    revision = "1605198800",
    sha256 = "75b08ce5db6c4522f6a66d192a1a5a2c4d576f378945c9ff22a46f828122f549",
)

CACERTS = struct(
    revision = "1605198800",
    sha256 = "9f9c04a0d3ba952b0db068a03ac546223a3d8955786cffef5a7fc66fdff5a251",
)
