# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

DEBS_TARBALL = struct(
    revision = "1592332390",
    sha256 = "2ebe6833f0c2826a54d811a78c3b1498d728f2dbfcc813fe6bb5270e0f419f96",
)

CACERTS = struct(
    revision = "1592332390",
    sha256 = "c31a03235e121c9e5704d4a511e27f1630dc203a0700adeb1019386a37bb5528",
)
