# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

timeout: "3600s"
options:
    machineType: "N1_HIGHCPU_32"

steps:
  - name: "gcr.io/asci-toolchain/nosla-ubuntu16_04-bazel-docker-gcloud"
    entrypoint: "bazel"
    args:
    - "--output_base=/workspace"
    - "test"
    - "--remote_instance_name=projects/asci-toolchain/instances/default_instance"
    - "--crosstool_top=@rbe_toolchain_config//cc:toolchain"
    - "--host_javabase=@rbe_toolchain_config//java:jdk"
    - "--javabase=@rbe_toolchain_config//java:jdk"
    - "--extra_toolchains=@rbe_toolchain_config//config:cc-toolchain"
    - "--extra_execution_platforms=//:platform_docker"
    - "--host_platform=//:platform_docker"
    - "--platforms=//:platform_docker"
    - "--action_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1"
    - "--host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8"
    - "--java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8"
    - "--spawn_strategy=remote"
    - "--strategy=Javac=remote"
    - "--strategy=Closure=remote"
    - "--genrule_strategy=remote"
    - "--define=EXECUTOR=remote"
    - "--remote_cache=remotebuildexecution.googleapis.com"
    - "--remote_executor=remotebuildexecution.googleapis.com"
    - "--tls_enabled=true"
    - "--remote_timeout=3600"
    - "--auth_enabled=true"
    - "--test_output=errors"
    - "--loading_phase_threads=1"
    - "//layers/..."
    waitFor: ["-"]

  # Install buildifier
  - name: "gcr.io/asci-toolchain/nosla-ubuntu16_04-bazel-docker-gcloud"
    entrypoint: "wget"
    args:
    - "-q"
    - "https://github.com/bazelbuild/buildtools/releases/download/0.20.0/buildifier"
    id: "buildifier-install"
    waitFor: ["-"]

  # Make the downloaded buildifier executable.
  - name: "gcr.io/asci-toolchain/nosla-ubuntu16_04-bazel-docker-gcloud"
    entrypoint: "chmod"
    args:
    - "+x"
    - "buildifier"
    id: "buildifier-enable"
    waitFor: ["buildifier-install"]

  # Run buildifier --mode=check.
  - name: "gcr.io/asci-toolchain/nosla-ubuntu16_04-bazel-docker-gcloud"
    entrypoint: "bash"
    args:
    - "-c"
    - "/workspace/buildifier --mode=check  $(find . -name BUILD -o -name WORKSPACE -o -name '*.bzl' -type f)"
    waitFor: ["buildifier-enable"]

  # Run buildifier --lint=warn.
  - name: "gcr.io/asci-toolchain/nosla-ubuntu16_04-bazel-docker-gcloud"
    entrypoint: "bash"
    args:
    - "-c"
    - "/workspace/buildifier --lint=warn $(find . -name BUILD -o -name WORKSPACE -o -name '*.bzl' -type f)"
    waitFor: ["buildifier-enable"]
