# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

BAZEL_INSTALLER = struct(
    revision = "1.0.0",
    sha256 = "f8490463360fff5992b5a5af93f930ff984588765f9ccf3e7dd03db5145fbf0f",
)

DEBS_TARBALL = struct(
    revision = "1568316709",
    sha256 = "78e569e68d4cf6577e75ad3da15ec35b0473987d75d5b0348d1eefc6a9ddba40",
)
