# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update serivce and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

BAZEL_INSTALLER = struct(
    revision = "0.23.0",
    sha256 = "7ea1baf4506af2f8a596052c675b43a8a8a36b737347b4f3d3466f0e202ea2a9",
)

DEBS_TARBALL = struct(
    revision = "20190228",
    sha256 = "860dbd5677f3ffaff4596df35bf72e7712423026bfb2a1382accdf48bb342525",
)
