# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

BAZEL_INSTALLER = struct(
    revision = "0.29.0",
    sha256 = "f2fbc65329ae9d3b7f86febe58ba82f9eb320003f93b3784e72c1c49d8d18745",
)

DEBS_TARBALL = struct(
    revision = "1563980495",
    sha256 = "6071af0905610f879b2e63fdc66378ec12fbba5adaca5cd9c258f95d50e2ad56",
)
