# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update serivce and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

DEBS_TARBALL = struct(
    revision = "20190204",
    sha256 = "49a360f90ff293aad630905052754311f341a304da9facc28623282f43e376d8",
)
