# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

DEBS_TARBALL = struct(
    revision = "1592332390",
    sha256 = "6e8c48c701a408cbefbe3e77e10d519dc02442820f8a28ece69f70a3ffc633e1",
)

CACERTS = struct(
    revision = "1592332390",
    sha256 = "f8aed064289af37523017e5c5d4e2b2f59ef7baeaf3400f1c1a239d43af3d4c0",
)
