# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

DEBS_TARBALL = struct(
    revision = "1578512061",
    sha256 = "66577190f4d6c617b18b8ef1e4cb43f930b98829d534e91f40b3b34d7200e1b9",
)

CACERTS = struct(
    revision = "1578512061",
    sha256 = "c6c1d219caf897836a9ff83f45181a91ebf0595c03767f6c303d6e4e57fb2092",
)
