# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

DEBS_TARBALL = struct(
    revision = "1612888386",
    sha256 = "08156901cb9a91a0505820e9ba2b696c48c9bb3624f798540797db3b9aeb6334",
)

CACERTS = struct(
    revision = "1612888386",
    sha256 = "74a785a86045d3279b39f8d7637b10fa33b83b5fab38075fa997d669694e00c5",
)
