# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

CLANG_INSTALLER = struct(
    revision = "88c9162c9d47ef43a505bc5301dc626f3cd4f437",
    sha256 = "c85551b78e9ebd95bf67969a7e0c8a3387d870c508106e84d8c11208afe6922b",
)

LIBCXX_INSTALLER = struct(
    revision = "88c9162c9d47ef43a505bc5301dc626f3cd4f437",
    sha256 = "5e4fea90da1d2187f998f458a989a2db2b39d32e5e9396e99cd8d7f0efa1cdfb",
)

DEBS_TARBALL = struct(
    revision = "1605051103",
    sha256 = "caf9d75ef67494390ac85374485ee58e5621b4a5715beefce6c16a8f8462ede0",
)
