# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

CLANG_INSTALLER = struct(
    revision = "90166c25631053eb4eaf5084358563ea268bb482",
    sha256 = "58950e8f75a7fefdd5a48ec77b0bc0e30f1b179888481398b32081d292d4b090",
)

LIBCXX_INSTALLER = struct(
    revision = "90166c25631053eb4eaf5084358563ea268bb482",
    sha256 = "ea02f1e13826a172b950e4df5ff0454b14998578edb070859ddbd909564e32f4",
)

DEBS_TARBALL = struct(
    revision = "1602631884",
    sha256 = "bd7647cd75aff14a0a7b95767f0aeaa59d338b4cb5fc11280e610d874276db20",
)
