# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update serivce and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

CLANG_INSTALLER = struct(
    revision = "r356196",
    sha256 = "435cad1dd1a49ecc756190580cbbb7523a8de900b6a8c7264cc853442e93fe5b",
)

LIBCXX_INSTALLER = struct(
    revision = "r356196",
    sha256 = "59d14140015540773923c109621e76598587a0a74d9fe0941483922941824f15",
)

DEBS_TARBALL = struct(
    revision = "20190402",
    sha256 = "18a375354bceadf88ba72eda5fc9ae83dcd39c0095eb712e589c356165216624",
)
