# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

CLANG_INSTALLER = struct(
    revision = "91087153210132a4c2d3cf19a4526d8f395cb5a4",
    sha256 = "b21781c9e462890f8ec1db669dc50c512b3760e64ce4b6bc5de1933972e3c6df",
)

LIBCXX_INSTALLER = struct(
    revision = "91087153210132a4c2d3cf19a4526d8f395cb5a4",
    sha256 = "c238f820ee4c8d2c6af1bd5adf1ac3e84015990d4f5e61c4de4241bc2c2f6ae8",
)

DEBS_TARBALL = struct(
    revision = "1589801487",
    sha256 = "bbbcc73252c291f0f0e4bc0d32b3e5626c434a993d4f990cfb5b8a627ef1322b",
)
