# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

CLANG_INSTALLER = struct(
    revision = "42cab985fd95ba4f3f290e7bb26b93805edb447d",
    sha256 = "743939018fe000d856496974d4589306a861fca69be7f7a6ea35ceda9b42330b",
)

LIBCXX_INSTALLER = struct(
    revision = "42cab985fd95ba4f3f290e7bb26b93805edb447d",
    sha256 = "6252826a08529fbd8e6a864fb08ee2cb151786ca4b264cfcc01a48e2923e7089",
)

DEBS_TARBALL = struct(
    revision = "1584711206",
    sha256 = "e3d9c35b2e54dc0cb886e21d6314fc7c2ad357ef6441b418ba89ea964447bed6",
)
