# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

CLANG_INSTALLER = struct(
    revision = "r370808",
    sha256 = "a4bf53c46a83e2640da4332496cd315440332585737bafc4e963f5b571f01b11",
)

LIBCXX_INSTALLER = struct(
    revision = "r370808",
    sha256 = "f9758640e014ae77bc5fc46e008fbfa19251b24dd7aa8e593a2faaf9be11051a",
)

DEBS_TARBALL = struct(
    revision = "1569936688",
    sha256 = "d2d5ae5a7fddbde29a2f6cde166294f7120821004e8742591d966d4bf990752b",
)
