# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update serivce and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

BAZEL_INSTALLER = struct(
    revision = "0.23.1",
    sha256 = "68620bacc994fb119009b2a4cbed90ca67a1ba43b22967e847b3e97673c4285e",
)

DEBS_TARBALL = struct(
    revision = "20190306",
    sha256 = "27d9603b194fa9951a543f317b6f2d63db6705ab4431a9dcfd28a130ecc5e391",
)
