# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update serivce and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

BAZEL_INSTALLER = struct(
    revision = "0.22.0",
    sha256 = "6d85f9fd6671ec5ffa8c78d150fe6c8da50874cfa8aa1900672dfd93e9989cb0",
)

DEBS_TARBALL = struct(
    revision = "20190207",
    sha256 = "408a400b74c04444f2ac7656535ce41919dc4abd84dab3d5547cb80ce2c900d9",
)
