# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

BAZEL_INSTALLER = struct(
    revision = "0.26.0",
    sha256 = "c6c67811e102eaa691938c2c3d420d2e220197b94e916e94076a0050cd93fd86",
)

DEBS_TARBALL = struct(
    revision = "1558559377",
    sha256 = "23dd64dd4bc84b4dd5b72cdb2ea5553f87396c9c75dc42f38225d731fccc3175",
)
