# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

DEBS_TARBALL = struct(
    revision = "1565715681",
    sha256 = "6343807b65a8752d1c00ad2d84d578c987a8219a3a5dabb7b79ea4524d36d530",
)
