# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

PY3_IMAGE = struct(
    sha256 = "sha256:555983e09df4410fe41ff2e72ac8a4d195031d94fb3a58f71f47682862b9b9ea",
)

DEBS_TARBALL = struct(
    revision = "1568759546",
    sha256 = "f064f9e8761d39f6fb48b598f13561d4a07ad5423d796c16fb3d20de3b694a62",
)
