# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

PY3_IMAGE = struct(
    sha256 = "sha256:55096029b76bcc83e6ddff5e2dc4198df657a912982920f12b9977863eae7173",
)

DEBS_TARBALL = struct(
    revision = "1565928075",
    sha256 = "69bc05a05a7a185e299d008c012626fb44f2389a023acd43b440efb548f25aaf",
)
