# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

OPENJDK_INSTALLER = struct(
    revision = "11.29.3-ca-jdk11.0.2/zulu11.29.3-ca-jdk11.0.2-linux_x64-allmodules-90755145cb6e6418584d8603cd5fa9afbb30aecc-1549209950",
    sha256 = "460d8a4f0c0204160b48086e341b22943c9cca471b195340e75b38ae9eb33c1c",
)

OPENJDK_SRC = struct(
    revision = "11.31.11-ca-jdk11.0.3/zsrc11.31.11-jdk11.0.3",
    sha256 = "65afc25dd914a094e25b1f804160bb20849f923d9a4b7d989f885558922e8182",
)

DEBS_TARBALL = struct(
    revision = "1561735077",
    sha256 = "31eacd8b2896369b982b62a42c6c3c082ba9ba9149a063b1f9231500f44d9b44",
)

CACERTS = struct(
    revision = "1561735113",
    sha256 = "2fe61973d42124aa6b78d181a08be4b712074787d6a1ea2769f48867ab7790ac",
)
